# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default
#  vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    jobs:
      - job: validate 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azure-terra-pipeline'
              backendAzureRmResourceGroupName: 'terraformstage'
              backendAzureRmStorageAccountName: 'terraformstagedarv'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'azure-terra-pipeline'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Azure Pass - Sponsorship(7279c7cc-0a34-404b-a374-0008fcbaa604)'